{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  labels: {{- include "merlin.labels" . | nindent 4 }}
  annotations:
    azure.workload.identity/client-id: {{ .Values.serviceAccount.workloadIdentityClientID | quote }}
{{- end }}
