apiVersion: v1
kind: Service
metadata:
  name: {{ include "merlin.fullname" . }}
  labels: {{- include "merlin.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector: {{- include "merlin.gateSelectorLabels" . | nindent 4 }}
  ports:
    - name: v2
      port: {{ .Values.service.port }}
      targetPort: 5000
      protocol: TCP
    - name: metrics
      port: {{ .Values.metrics.port }}
      targetPort: 9090
      protocol: TCP
